commerce_fraud.rules.*:
  type: config_entity
  label: 'Rules'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: commerce_fraud.rules.plugin.[%parent.plugin]
    counter:
      type: integer
      label: 'Counter'
commerce_fraud.rules.plugin.*:
  type: commerce_fraud_rules_configuration

commerce_fraud_rules_configuration:
  type: mapping
  mapping:
    last_minute:
      type: integer
      label: 'Last Minute'
    buy_amount:
      type: mapping
      label: 'Price'
      mapping:
        number:
          type: integer
          label: 'number'
        currency_code:
          type: string
          label: 'currency_code'
    buy_quantity:
      type: integer
      label: 'Quantity'
    product_conditions:
      type: commerce_condition_configuration
      label: 'Product Conditions'
    fraudulent_orders:
      type: integer
      label: 'Fraudulent Orders'
    user_id:
      type: integer
      label: 'User Id'
    user_name:
      type: string
      label: 'User Name'
    user_email:
      type: string
      label: 'User Email'
    user_field:
      type: string
      label: 'User Field'
    order_id:
      type: integer
      label: 'Order Id'
    order_country_code:
      type: string
      label: 'Order Country Code'
    order_first_name:
      type: string
      label: 'Order First Name'
    order_company_name:
      type: string
      label: 'Order Company Name'
    order_street_address:
      type: string
      label: 'Order Street Address'
    order_administrative_area:
      type: string
      label: 'Order Administrative Area'
    order_locality:
      type: string
      label: 'Order Locality'
    order_area_code:
      type: integer
      label: 'Order Area Code'
    order_field:
      type: string
      label: 'Order Field'
